apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-container
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-container
  template:
    metadata:
      labels:
        app: flask-container
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: flask-container
        image: devop5guy/flask-container:0.1.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
        ports:
        - containerPort: 3000
