apiVersion: v1
kind: Service
metadata:
  name: flask-container
  namespace: kube-system
spec:
  type: ExternalName
  externalName: flask-container.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: flask-container
spec:
  selector:
    app: flask-container
  ports:
  - port: 3000
